[package]
name = "runen-render"
version = "0.1.0"
edition = "2024"
rust-version = "1.93.0"
license.workspace = true
repository = "https://github.com/dornglut/runen-render"
description = "Reusable semantic rendering and maintained image-formation framework"
publish = false

[features]
default = []

[dependencies]
runen-gpu = { git = "https://github.com/dornglut/runen-gpu", rev = "789b430fdefeda89bfe59de86d548618b8f8ab9a" }
runen-shader = { git = "https://github.com/dornglut/runen-shader", rev = "406f8165da92caa2d296b3a2f774ba534279870d" }

[dev-dependencies]
pollster = "0.4.0"

[workspace]
resolver = "3"
members = ["xtask"]

[workspace.package]
edition = "2024"
license = "GPL-3.0-only"

[lints]
workspace = true

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
