[package]
name = "runen-render"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license.workspace = true
repository = "https://github.com/dornglut/runen-render"
description = "Reusable semantic rendering and maintained image-formation framework"
publish = false

[features]
default = []

[dependencies]
bymsdfgen-core = { version = "=0.1.1", default-features = false }
runen-gpu = { git = "https://github.com/dornglut/runen-gpu", rev = "7a833e750bc92b28f05b2c8507e326660f100a1e" }
runen-shader = { git = "https://github.com/dornglut/runen-shader", rev = "406f8165da92caa2d296b3a2f774ba534279870d" }
skrifa = { version = "=0.44.0", default-features = false, features = ["std"] }

[dev-dependencies]
pollster = "0.4.0"

[workspace]
resolver = "3"
members = ["xtask"]

[workspace.package]
edition = "2024"
license = "GPL-3.0-only"

[lints]
workspace = true

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
